/**
 * Classe que define a model "Rate"
 *
 * =======================================
 * ###################################
 * MagnusBilling
 *
 */
Ext.define('MBilling.model.Rate', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'id',
        type: 'int'
    }, {
        name: 'id_plan',
        type: 'int'
    }, {
        name: 'id_trunk_history',
        type: 'int'
    }, {
        name: 'id_trunk_group',
        type: 'int'
    }, {
        name: 'id_trunk_group2',
        type: 'int'
    }, {
        name: 'id_trunk_group3',
        type: 'int'
    }, {
        name: 'FNCalled',
        type: 'string'
    }, {
        name: 'FNCaller',
        type: 'string'
    }, {
        name: 'FRCalled',
        type: 'string'
    }, {
        name: 'FRCaller',
        type: 'string'
    }, {
        name: '2min',
        type: 'string'
    }, {
        name: 'att2min',
        type: 'string'
    }, {
        name: '5min',
        type: 'string'
    }, {
        name: 'att5min',
        type: 'string'
    }, {
        name: '15min',
        type: 'string'
    }, {
        name: 'att15min',
        type: 'string'
    }, {
        name: '1h',
        type: 'string'
    }, {
        name: 'att4h',
        type: 'string'
    }, {
        name: '4h',
        type: 'string'
    }, {
        name: 'att1h',
        type: 'string'
    }, {
        name: '1d',
        type: 'string'
    }, {
        name: 'att1d',
        type: 'string'
    }, {
        name: 'id_prefix',
        type: 'int'
    }, {
        name: 'rateinitial',
        type: 'number'
    }, {
        name: 'initblock',
        type: 'int'
    }, {
        name: 'billingblock',
        type: 'int'
    }, {
        name: 'connectcharge',
        type: 'number'
    }, {
        name: 'disconnectcharge',
        type: 'number'
    }, {
        name: 'additional_grace',
        type: 'string'
    }, {
        name: 'minimal_cost',
        type: 'int'
    }, {
        name: 'minimal_time_charge',
        type: 'int'
    }, {
        name: 'package_offer',
        type: 'int'
    }, {
        name: 'status',
        type: 'int'
    }, 'idPrefixdestination', 'idPrefixprefix', 'idTrunkGroupname', 'idTrunkGroup2name', 'idTrunkGroup3name', 'idPlanname'],
    proxy: {
        type: 'uxproxy',
        module: 'rate'
    }
});